/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import com.ggalmazor.ltdownsampling.DoublePoint;
import com.ggalmazor.ltdownsampling.LTThreeBuckets;
import com.ggalmazor.ltdownsampling.Point;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Random;

public class App {
    public static void main(String[] args) {
        List<Point> input = new ArrayList<>();
        while (input.size() < 1_000_000)
            input.add(new DoublePoint(input.size(), new Random(123456L).nextDouble()));

        List<Point> output = LTThreeBuckets.sorted(input, 500);
        System.out.println(Arrays.toString(output.toArray()));
    }
}
